added InstructorEmbeddingFuntion documentation
chroma-core/docs pull request #19
Opened 2023-03-24 19:39 UTC by dbasch

Included link to the instructor repo and usage examples.

2023-03-24 19:56 UTC, jeffchuber requested changes

2023-03-24 19:56 UTC, jeffchuber commented on docs/embeddings.md
>  ### Multilingual model example
@dbasch can you move instructor below the multilingual section? the Cohere section got split into 2 here. tahnks!

2023-03-25 01:18 UTC, dbasch commented
Sure

On Fri, Mar 24, 2023 at 12:56 PM Jeff Huber ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In docs/embeddings.md
> <https://github.com/chroma-core/docs/pull/19#discussion_r1148001855>:
>
> > +The [instructor-embeddings](https://github.com/HKUNLP/instructor-embedding) library is another option, especially when running on a machine with a cuda-capable GPU. They are a good local alternative to OpenAI (see the [Massive Text Embedding Benchmark](https://huggingface.co/blog/mteb) rankings).  The embedding function requires the InstructorEmbedding package. To install it, run ```pip install InstructorEmbedding```.
> +
> +There are three models available. The default is `hkunlp/instructor-base`, and for better performance you can use `hkunlp/instructor-large` or `hkunlp/instructor-xl`. You can also specify whether to use `cpu` (default) or `cuda`. For example:
> +
> +```python
> +#uses base model and cpu
> +ef = embedding_functions.InstructorEmbeddingFunction()
> +```
> +or
> +```python
> +ef = embedding_functions.InstructorEmbeddingFunction(
> +model_name="hkunlp/instructor-xl", device="cuda")
> +```
> +Keep in mind that the large and xl models are 1.5GB and 5GB respectively, and are best suited to running on a GPU.
> +
> +
>  ### Multilingual model example
>
> @dbasch <https://github.com/dbasch> can you move instructor below the
> multilingual section? the Cohere section got split into 2 here. tahnks!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/chroma-core/docs/pull/19#pullrequestreview-1357346006>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAC5VVFU6RQNSQLDJKXZOGDW5X363ANCNFSM6AAAAAAWG6YJJA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-03-25 04:20 UTC, jeffchuber approved these changes
thanks!

2023-03-25 04:20 UTC, merged